### ISSUE TITLE
Not able to log into the app

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/synapse-admin_ynh#42]
This is a follow up on [this forum thread](https://forum.yunohost.org/t/synapse-taking-too-much-resources/26696/3).

### Describe the bug

I'm not able to use synapse-admin, installing seem to be working fine, but when I open synapse admin and enter my homeserver url, I'm asked to "sign in with sso", I do it log in, get redirected to the sso portal, and nothing more, if I go back to synapse admin it asks again to sign in.

### Context

Hardware: VM in a computer
YunoHost version: 11.2.4
I have access to my server : Through SSH, through the webadmin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no
Synapse version: 1.92.3~ynh1

### Debugging things I tried

I checked the following:
 - “Synapse (Server administration API.)” permission is given to visitors, sounds a bit extreme to me, but I didn’t do it, maybe installing Synapse admin did it.
 - The user I try to log in with is a synapse administrator (at least I ran the following command: su --command="psql matrix_synapse" postgres <<< "UPDATE users SET admin = 1 WHERE name = '@user2beAdmin:domain.tld'" with the appropriate username and domain).

I’m running out of ideas of what could be going wrong. But it definitely seems to be that Synapse admin doesn’t manage to have access to synapse administration api, since in the web console it logs: GET https://synapsedomain.tld/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=name [HTTP/2 401 Unauthorized 165ms]

**Comment by Bugsbane** [comment]
I'm getting the same error. Element Android and Element Web (also hosted on Yunohost) had been working fine. I logged out of both to perform an experiment and now on both, I'm unable to log in. When I try, first they ask me to enter my home server and click "Continue with CAS":
![image4576](https://github.com/YunoHost-Apps/synapse-admin_ynh/assets/401733/9a261720-a90f-40e4-a60f-ad2f31f7dd91)

When I click that, both Element Web and Element Android just take me to MYDOMAIN.TLD/yunohost/sso/:
![image21854](https://github.com/YunoHost-Apps/synapse-admin_ynh/assets/401733/2ac3ed41-b2c1-4e8b-a19b-3c8276e8ab3b)

Entering Matrix.org instead seems to work fine, so it seems to be a synapse_ynh or SSO issue, rather than a client or Synapse issue. I don't see any parameters in the URL, like token or anything like that. Should there be?

## Context: ##
Hardware: VPS
YunoHost versions: 
yunohost: 
  repo: stable
  version: 11.2.4
yunohost-admin: 
  repo: stable
  version: 11.2.2
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2

I have access to my server : Through SSH, and through the webadmin if I chosse to re-enable yunohost-api
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : I recently edited my nginx file for nextcloud.conf ([contents here](https://paste.yunohost.org/cosuluneve.nginx)), as outlined [in this forum thread](https://forum.yunohost.org/t/nextcloud-has-issued-fix-for-a-conf-issue-how-to-manually-apply-to-yunohost/26687 ), but other than that, no.
Synapse version: 1.92.3~ynh1


## Miscelaneous: ##
My >80 year old family member is traveling solo right now and this is the family's main way to communicate with them, so anything I can do to help debug this issue quickly, please let me know so I can provide any useful info asap!

Is there a safe way to revert synapse to the last backup, so I can see if that helps?

Thanks!

**Comment by Bugsbane** [comment]
Weird! When I try this, the CLI asks for my password and about 1.5 seconds later says "Authentication failure" without me ever hitting enter and before even letting me try to type my password!

**Comment by link-leo** [comment]
I am also unable to log-in through the web portal. After entering my credentials and server address, using either sign on or sign on with sso, it appears to load the interface for half a second and then immediately takes me back to the log-in page with a red error message saying `Your session has ended, please reconnect.` I get the same results in every browser and device combination I try.

**Comment by link-leo** [comment]
I was able to log in by following [these instructions](https://m.opnxng.com/how-to-fix-error-password-authentication-failed-for-the-user-in-postgresql-896e1fd880dc) to change `/etc/postgresql/<postgresql version>/main/pg_hba.conf` by adding `trust` to the `postgres` user and then logging into the the `matrix_synapse` db via `psq` and running the command `UPDATE users SET admin = 1 WHERE name = '@user2beAdmin:domain.tld'`, though the full string `su --command="psql matrix_synapse" postgres <<< "UPDATE users SET admin = 1 WHERE name = '@user2beAdmin:domain.tld'"` as commented above *still* did not work. I'm now able to access the Synapse Admin UI.

**Comment by Bugsbane** [comment]
I think this may be a dupe of https://github.com/YunoHost-Apps/synapse_ynh/issues/412 .

**Comment by eauchat** [comment]
The last update of `synapse_ynh` (1.105.0~ynh1) seems to be improving the situation for me. If you set synapse to accept connection via password (from yunohost admin synapse config panel), it's possible to log in to synapse admin.
The sso connection is still behaving strange. But not sure it's a problem from `synapse-admin_ynh`, it may be residing in quirks between synapse and sso.
I'll close the issue, but if someone wants me to reopen it feel free to say so.
